const TYPES = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_LIST_TECH: 'SET_LIST_TECH',
  INIT_FILTER: 'INIT_FILTER',
  ADD_FAVORITE: 'ADD_FAVORITE',
  DELETE_FAVORITE: 'DELETE_FAVORITE',
};

export default TYPES;
